[package]
name = "oaf"
version = "0.1.0"
edition = "2021"
license-file = "LICENSE"
description = "An open source binary file format for archery scoring"
repository = "https://github.com/TommyGymer/OAF"
readme = "README.md"

[dependencies]
